[package]
name = "json"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.210" }
serde_json = "1.0.128"

[dev-dependencies]
serde = { version = "1.0.210", features = ["derive"] }
