[package]
name = "json"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.213" }
serde_json = "1.0.132"

[dev-dependencies]
serde = { version = "1.0.213", features = ["derive"] }
