[package]
name = "json"
version = "0.2.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.219" }
serde_json = "1.0.140"

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
